In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import ShuffleSplit,LeavePGroupsOut

## 随机排列交叉验证

In [3]:
X=np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
s=ShuffleSplit(n_splits=2,test_size=0.2,random_state=1)
train,test=s.split(X)
print(train,test)

(array([6, 4, 0, 3, 1, 7, 8, 5]), array([2, 9])) (array([3, 0, 8, 4, 2, 1, 6, 7]), array([9, 5]))


## 分层K交叉验证

In [33]:
from sklearn.model_selection import StratifiedKFold

X=np.ones(10)
Y=[0,0,0,0,1,1,1,1,1,1]
skf=StratifiedKFold(n_splits=3,shuffle=False)
for train_index,test_index in skf.split(X,Y):
    print(train_index,test_index)

[2 3 6 7 8 9] [0 1 4 5]
[0 1 3 4 5 8 9] [2 6 7]
[0 1 2 4 5 6 7] [3 8 9]


In [24]:
X=np.arange(6)
Y=np.random.randint(1,5,6)
Z=[1,1,2,2,3,3]
print(X,Y,Z)
lpgo=LeavePGroupsOut(n_groups=1)
for train_index,test_index in lpgo.split(X,Y,groups=Z): #输出的全是index
    print(train_index,test_index)

[0 1 2 3 4 5] [2 1 3 4 3 2] [1, 1, 2, 2, 3, 3]
[2 3 4 5] [0 1]
[0 1 4 5] [2 3]
[0 1 2 3] [4 5]


## 时间序列分割

In [34]:
from sklearn.model_selection import TimeSeriesSplit

X=np.array([[1,2],
            [3,4],
            [1,2],
            [3,4],
            [1,2],
            [3,4],
            [2,2],
            [4,6]
           ])
Y=np.arange(1,9)

tscv=TimeSeriesSplit(n_splits=3,max_train_size=3)
for train_index,test_index in tscv.split(X,Y):
    print(train_index,test_index)

[0 1] [2 3]
[1 2 3] [4 5]
[3 4 5] [6 7]


## 交叉验证综合评分

In [41]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn import datasets
iris=datasets.load_iris()
clf=SVC(kernel='linear')
scores=cross_val_score(clf,iris.data,iris.target,cv=5) #5折交叉验证
print(scores)
print(r'Accuracy:%0.2f(+/-)%0.2f %%'%(scores.mean(),scores.std()*2))

[0.96666667 1.         0.96666667 0.96666667 1.        ]
Accuracy:0.98(+/-)0.03 %


In [43]:
#通过传入验证迭代器来指定验证策略

from sklearn.model_selection import ShuffleSplit

n_samples=iris.data.shape[0]
ss=ShuffleSplit(n_splits=3,test_size=1/3,random_state=1)
cross_val_score(clf,iris.data,iris.target,cv=ss)

array([1.  , 0.96, 1.  ])

In [44]:
#corss_validate和cross_val_score相似但更强大，可以返回fit_time和score_time

from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

scores=cross_validate(clf,iris.data,iris.target,scoring=['f1_macro','f1_micro'],cv=3,return_train_score=False)
print(scores)


{'fit_time': array([0.00075698, 0.00054288, 0.0004859 ]), 'score_time': array([0.0018661 , 0.00135779, 0.00133133]), 'test_f1_macro': array([1.        , 1.        , 0.98037518]), 'test_f1_micro': array([1.  , 1.  , 0.98])}


In [ ]:
from sklearn.linear_model import ElasticNetCV,LogisticRegressionCV,RidgeClassifierCV
