In [25]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler,MinMaxScaler,MaxAbsScaler,RobustScaler,Normalizer,Binarizer

## MinMax缩放

In [2]:
data=load_boston()

df=pd.DataFrame(data.data,columns=data.feature_names)
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [4]:
#MinMax缩放

minmaxsclaer=MinMaxScaler(feature_range=(0,1))
minmaxsclaer.fit_transform(df).shape

(506, 13)

## RobustScaler

In [11]:
ar=np.array([10,1000,0,0,-30,0,20,0,10,0,0,-10]).reshape(-1,1)
ar

array([[  10],
       [1000],
       [   0],
       [   0],
       [ -30],
       [   0],
       [  20],
       [   0],
       [  10],
       [   0],
       [   0],
       [ -10]])

In [12]:
robustscaler=RobustScaler(quantile_range=(25,75))
robustscaler.fit_transform(ar)

array([[  1.],
       [100.],
       [  0.],
       [  0.],
       [ -3.],
       [  0.],
       [  2.],
       [  0.],
       [  1.],
       [  0.],
       [  0.],
       [ -1.]])

## MaxAbsSclaer(一般用于稀疏矩阵)

In [15]:
ar1=np.array([[0]*95+[0,20,0,10,-10]]).reshape(-1,1)

In [17]:
maxabsscaler=MaxAbsScaler()
maxabsscaler.fit_transform(ar1)[:10]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

# 数据的正规化

In [19]:
x2=np.random.randint(-1,3,(3,3))
x2

array([[ 1,  0, -1],
       [ 0,  1, -1],
       [ 2,  2, -1]])

In [22]:
normalizer=Normalizer(norm='l2')
normalizer.fit_transform(x2)

array([[ 0.70710678,  0.        , -0.70710678],
       [ 0.        ,  0.70710678, -0.70710678],
       [ 0.66666667,  0.66666667, -0.33333333]])

# 数据的二值化

In [24]:
x2

array([[ 1,  0, -1],
       [ 0,  1, -1],
       [ 2,  2, -1]])

In [27]:
binarizer=Binarizer(threshold=0)
binarizer.fit_transform(x2)

array([[1, 0, 0],
       [0, 1, 0],
       [1, 1, 0]])