In [10]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
measurements=[
    {'city':'Dubai','temperature':33,},
    {'city':'London','temperature':12},
    {'city':'San Francisco','temperature':18}
]
measurements

[{'city': 'Dubai', 'temperature': 33},
 {'city': 'London', 'temperature': 12},
 {'city': 'San Francisco', 'temperature': 18}]

In [9]:
vec=DictVectorizer()
print(vec.fit_transform(measurements).toarray())
print(vec.get_feature_names())

[[ 1.  0.  0. 33.]
 [ 0.  1.  0. 12.]
 [ 0.  0.  1. 18.]]
['city=Dubai', 'city=London', 'city=San Francisco', 'temperature']


## 词频向量转换

In [15]:
coprus=[
    'UNC played Duke in basketball',
    'Duke lost the basketball game and the game is over',
    'I ate a sandwich'
]

vectorizer=CountVectorizer(stop_words='english')
print(vectorizer.fit_transform(coprus).todense())
print(vectorizer.vocabulary_)

[[0 1 1 0 0 1 0 1]
 [0 1 1 2 1 0 0 0]
 [1 0 0 0 0 0 1 0]]
{'unc': 7, 'played': 5, 'duke': 2, 'basketball': 1, 'lost': 4, 'game': 3, 'ate': 0, 'sandwich': 6}


In [17]:
!pip install jieba

     |█████████████▎                  | 8.0 MB 9.2 kB/s eta 0:20:189^C

ERROR: Operation cancelled by user


In [18]:
!pip install jieba -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     |████████████████████████████████| 19.2 MB 646 kB/s eta 0:00:01
  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314478 sha256=4cce080b72d6b25b7087871b4fb1d22fa0ead8be4bafdbed5a7154dcdebd3f1a
  Stored in directory: /Users/hurrywish/Library/Caches/pip/wheels/95/1a/6d/75355e7a5c76ed48e2d6cde3b95c4828e83274b93f5392ac96
Successfully built jieba
