In [15]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,Normalizer

# 标签化和独热化

In [12]:
data=np.array(['UP','DOWN','UP','DOWN','MED'])

In [13]:
le=LabelEncoder()
data1=le.fit_transform(data)
data1.reshape(-1,1)

array([[2],
       [0],
       [2],
       [0],
       [1]])

In [14]:
ohe=OneHotEncoder().fit_transform(data1.reshape(-1,1))
ohe.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

# 正规化

In [27]:
data3=np.array([[1,-2,3,4,-5,36,7,49,56]]) #转成列
result1=Normalizer(norm='l1').fit_transform(data3)
result2=Normalizer(norm='l2').fit_transform(data3)
print(result1,result2)

[[ 0.00613497 -0.01226994  0.01840491  0.02453988 -0.03067485  0.2208589
   0.04294479  0.3006135   0.34355828]] [[ 0.01200644 -0.02401287  0.03601931  0.04802575 -0.06003219  0.43223174
   0.08404506  0.58831542  0.67236048]]


In [28]:
np.array([1,-2,3,4,-5,36,7,49,56]).T

array([ 1, -2,  3,  4, -5, 36,  7, 49, 56])

In [29]:
np.array([[1,-2,3,4,-5,36,7,49,56]])

array([[ 1, -2,  3,  4, -5, 36,  7, 49, 56]])

# LDA降维

In [30]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [32]:
X=np.array([[-1,-2],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
Y=np.array([1,1,1,2,2,2])

In [34]:
lda=LinearDiscriminantAnalysis(n_components=1)
clf=lda.fit(X,Y)
clf.predict([[0.8,1]]) #Fisher分类器

array([2])

# 特征衍生