In [17]:
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_selection import SelectKBest,RFE,SelectFromModel
from sklearn.svm import SVR

In [12]:
data=pd.DataFrame({'A':stats.norm.rvs(size=10),'B':stats.norm.rvs(size=10),'C':stats.norm.rvs(size=10),'D':np.random.randint(0,2,10)})

In [13]:
data

A         B         C  D
0  0.550925  0.328911 -0.236755  0
1  1.812289  0.492305 -1.890470  0
2  0.673952 -0.027319  0.218152  0
3  0.238329 -1.098172  2.101356  1
4  0.889976 -0.222266 -0.778928  1
5  0.343031  0.368183 -0.548536  1
6  0.590563 -1.127773  2.403875  1
7 -1.066955  0.975949  0.642373  1
8 -0.310151 -1.383852 -2.333076  1
9  1.783430  0.806869  1.449443  1

In [14]:
X=data[['A','B','C']]
Y=data['D']

In [15]:
skb=SelectKBest(k=2)
skb.fit(X,Y)
skb.transform(X)

array([[ 0.55092516, -0.23675538],
       [ 1.81228859, -1.89046967],
       [ 0.67395212,  0.21815247],
       [ 0.23832903,  2.10135575],
       [ 0.88997635, -0.77892821],
       [ 0.34303105, -0.54853563],
       [ 0.59056275,  2.40387452],
       [-1.06695482,  0.64237307],
       [-0.31015091, -2.33307598],
       [ 1.78343039,  1.44944331]])

In [19]:
rfe=RFE(estimator=SVR(kernel='linear'),n_features_to_select=2,step=1)
rfe.fit_transform(X,Y)

array([[ 0.55092516,  0.3289113 ],
       [ 1.81228859,  0.49230474],
       [ 0.67395212, -0.02731947],
       [ 0.23832903, -1.09817229],
       [ 0.88997635, -0.2222664 ],
       [ 0.34303105,  0.36818345],
       [ 0.59056275, -1.12777262],
       [-1.06695482,  0.97594874],
       [-0.31015091, -1.38385173],
       [ 1.78343039,  0.80686946]])

In [23]:
sfm=SelectFromModel(estimator=DecisionTreeRegressor(),threshold=0.5)
sfm.fit_transform(X,Y)

array([[-0.23675538],
       [-1.89046967],
       [ 0.21815247],
       [ 2.10135575],
       [-0.77892821],
       [-0.54853563],
       [ 2.40387452],
       [ 0.64237307],
       [-2.33307598],
       [ 1.44944331]])