In [61]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from functools import reduce
%matplotlib inline

In [16]:
columns=[['junior','junior','youth','youth'],['Zhang','Wang','Li','Zhao']]
index=[['morning','morning','morning','afternoon','afternoon','afternoon'],[1,2,3,1,2,3]]
data=np.array([[31,27,24,60],[26,28,13,29],[27,17,12,27],[29,9,5,18],[31,12,4,70],[45,11,12,12]])
Gamedata=pd.DataFrame(data,columns=columns,index=index)

In [17]:
Gamedata

junior      youth     
             Zhang Wang    Li Zhao
morning   1     31   27    24   60
          2     26   28    13   29
          3     27   17    12   27
afternoon 1     29    9     5   18
          2     31   12     4   70
          3     45   11    12   12

In [18]:
Gamedata['junior']['Zhang'].loc['morning'].loc[1] #按照行的索引

31

In [27]:
Gamedata['youth'].loc['morning'].loc[1:2,'Li'] #观察数值索引是否是默认的还是设置的

1    24
2    13
Name: Li, dtype: int64

In [28]:
Gamedata['youth'].loc['morning'].loc[1:2,'Li':'Zhao']

Li  Zhao
1  24    60
2  13    29

In [29]:
Gamedata.junior.loc[[('morning',1),('afternoon',2)]] #跨区索引

Zhang  Wang
morning   1     31    27
afternoon 2     31    12

# 索引的互换

In [30]:
Gamedata_1=Gamedata.copy()

In [33]:
Gamedata_1.columns.names=['age','family_name'] #给次外层命名
Gamedata_1.index.names=['times','series']
Gamedata_1

age              junior      youth     
family_name       Zhang Wang    Li Zhao
times     series                       
morning   1          31   27    24   60
          2          26   28    13   29
          3          27   17    12   27
afternoon 1          29    9     5   18
          2          31   12     4   70
          3          45   11    12   12

In [36]:
Gamedata_1.swaplevel('age','family_name',axis=1)

family_name       Zhang   Wang    Li  Zhao
age              junior junior youth youth
times     series                          
morning   1          31     27    24    60
          2          26     28    13    29
          3          27     17    12    27
afternoon 1          29      9     5    18
          2          31     12     4    70
          3          45     11    12    12

In [38]:
Gamedata_1.swaplevel('times','series',axis=0)

age              junior      youth     
family_name       Zhang Wang    Li Zhao
series times                           
1      morning       31   27    24   60
2      morning       26   28    13   29
3      morning       27   17    12   27
1      afternoon     29    9     5   18
2      afternoon     31   12     4   70
3      afternoon     45   11    12   12

# 排序

In [48]:
Gamedata_1.sort_index(axis=0,level=1) #第一个数字是选择行或列索引，第二个数字是级别

age              junior      youth     
family_name       Zhang Wang    Li Zhao
times     series                       
afternoon 1          29    9     5   18
morning   1          31   27    24   60
afternoon 2          31   12     4   70
morning   2          26   28    13   29
afternoon 3          45   11    12   12
morning   3          27   17    12   27

In [42]:
Gamedata_1

age              junior      youth     
family_name       Zhang Wang    Li Zhao
times     series                       
morning   1          31   27    24   60
          2          26   28    13   29
          3          27   17    12   27
afternoon 1          29    9     5   18
          2          31   12     4   70
          3          45   11    12   12

In [47]:
Gamedata_1.sum(axis=0,level=1)

age         junior      youth     
family_name  Zhang Wang    Li Zhao
series                            
1               60   36    29   78
2               57   40    17   99
3               72   28    24   39

In [50]:
Gamedata_1.sum(axis=0,level=0)

age         junior      youth     
family_name  Zhang Wang    Li Zhao
times                             
morning         84   72    49  116
afternoon      105   32    21  100

In [53]:
Gamedata_1.sum(axis=1,level=0)

age               junior  youth
times     series               
morning   1           58     84
          2           54     42
          3           44     39
afternoon 1           38     23
          2           43     74
          3           56     24

# 水平拼接 hstack

In [59]:
data1=np.random.randint(1,5,10)
data2=np.random.randint(10,50,10)

In [60]:
data=np.hstack([data1,data2])
data

array([ 4,  1,  3,  3,  1,  2,  2,  1,  1,  3, 49, 10, 41, 32, 37, 25, 42,
       30, 21, 21])

In [ ]:
# 两个二维数组需要行数相同

# 竖直拼接 vstack

In [64]:
data1=np.random.randint(1,5,10)
data2=np.random.randint(10,50,10)
data=np.vstack([data1,data2])
data

array([[ 2,  1,  3,  1,  1,  2,  3,  2,  1,  1],
       [40, 10, 27, 30, 38, 23, 45, 19, 20, 47]])

In [ ]:
# 两个二维数组需要列数相同

In [69]:
argroup=[np.random.uniform(2,10,(j,7)) for j in range(2,5)]
argroup

[array([[3.40431751, 9.87899661, 5.76275094, 3.96174016, 6.88304882,
         6.46419328, 7.78348729],
        [8.37457162, 4.50932501, 4.32823038, 9.38103881, 8.79004299,
         9.46494844, 7.141208  ]]),
 array([[4.25361425, 2.42703708, 2.96820296, 8.07610376, 8.88305824,
         9.72470152, 9.58717966],
        [9.85925115, 6.20813477, 2.15441194, 5.51538644, 7.08002603,
         2.50338191, 8.49306338],
        [3.03856255, 8.75083916, 6.32927659, 9.34014299, 3.8682592 ,
         6.41267618, 8.31571695]]),
 array([[5.61912653, 4.84502754, 7.29129394, 6.55483754, 8.21975736,
         6.90482505, 4.67615269],
        [9.85633476, 4.16458178, 7.73616994, 3.86519923, 6.24814339,
         6.13583094, 6.0645883 ],
        [8.17112017, 2.28571188, 5.30897609, 4.51398297, 5.82135778,
         9.17772446, 8.58464586],
        [5.00359435, 4.55237173, 5.77831547, 3.78256412, 5.14784293,
         6.62824383, 8.36735591]])]

In [70]:
np.vstack(argroup)

array([[3.40431751, 9.87899661, 5.76275094, 3.96174016, 6.88304882,
        6.46419328, 7.78348729],
       [8.37457162, 4.50932501, 4.32823038, 9.38103881, 8.79004299,
        9.46494844, 7.141208  ],
       [4.25361425, 2.42703708, 2.96820296, 8.07610376, 8.88305824,
        9.72470152, 9.58717966],
       [9.85925115, 6.20813477, 2.15441194, 5.51538644, 7.08002603,
        2.50338191, 8.49306338],
       [3.03856255, 8.75083916, 6.32927659, 9.34014299, 3.8682592 ,
        6.41267618, 8.31571695],
       [5.61912653, 4.84502754, 7.29129394, 6.55483754, 8.21975736,
        6.90482505, 4.67615269],
       [9.85633476, 4.16458178, 7.73616994, 3.86519923, 6.24814339,
        6.13583094, 6.0645883 ],
       [8.17112017, 2.28571188, 5.30897609, 4.51398297, 5.82135778,
        9.17772446, 8.58464586],
       [5.00359435, 4.55237173, 5.77831547, 3.78256412, 5.14784293,
        6.62824383, 8.36735591]])

# concatenate

In [75]:
data1=np.random.randint(1,5,10)
data2=np.random.randint(10,50,10)
np.concatenate([data1,data2])

array([ 4,  1,  4,  1,  4,  3,  3,  1,  2,  4, 28, 45, 28, 18, 46, 16, 39,
       21, 43, 27])

In [76]:
# concatenate要求必须拼接的对象维度相同

# column_stack row_stack

In [77]:
s1=[np.random.randint(1,11,6) for j in range(5)]
s1

[array([ 6,  9,  7, 10,  4,  4]),
 array([ 3, 10,  6,  4,  2,  4]),
 array([10,  5,  9,  4,  6,  1]),
 array([ 9,  7,  6,  3,  5, 10]),
 array([ 9,  7,  9,  4,  8, 10])]

In [78]:
np.column_stack([s1[0],s1[2]]) #把一维数组作为列拼接

array([[ 6, 10],
       [ 9,  5],
       [ 7,  9],
       [10,  4],
       [ 4,  6],
       [ 4,  1]])

In [79]:
s2=[np.random.randint(2,12,(8,j)) for j in range(5)]
s2

[array([], shape=(8, 0), dtype=int64),
 array([[ 5],
        [ 6],
        [10],
        [ 4],
        [ 5],
        [ 2],
        [ 5],
        [ 2]]),
 array([[ 6,  3],
        [ 9, 11],
        [ 2,  8],
        [ 4,  3],
        [10,  7],
        [ 9,  8],
        [ 2, 10],
        [ 7,  7]]),
 array([[ 7,  4, 11],
        [ 8, 10,  2],
        [ 9,  3,  7],
        [ 6,  5,  7],
        [11,  7,  6],
        [11,  6,  8],
        [ 9,  7,  4],
        [10,  4,  4]]),
 array([[10,  7,  2, 10],
        [10, 11,  9,  3],
        [ 7, 10,  6,  9],
        [10,  9,  4, 11],
        [ 8,  7, 10,  4],
        [ 2,  4,  8, 11],
        [ 8,  8,  8,  5],
        [ 9,  7,  8,  3]])]

In [86]:
np.column_stack(s2)

array([[ 5,  6,  3,  7,  4, 11, 10,  7,  2, 10],
       [ 6,  9, 11,  8, 10,  2, 10, 11,  9,  3],
       [10,  2,  8,  9,  3,  7,  7, 10,  6,  9],
       [ 4,  4,  3,  6,  5,  7, 10,  9,  4, 11],
       [ 5, 10,  7, 11,  7,  6,  8,  7, 10,  4],
       [ 2,  9,  8, 11,  6,  8,  2,  4,  8, 11],
       [ 5,  2, 10,  9,  7,  4,  8,  8,  8,  5],
       [ 2,  7,  7, 10,  4,  4,  9,  7,  8,  3]])

In [85]:
np.hstack(s2)

array([[ 5,  6,  3,  7,  4, 11, 10,  7,  2, 10],
       [ 6,  9, 11,  8, 10,  2, 10, 11,  9,  3],
       [10,  2,  8,  9,  3,  7,  7, 10,  6,  9],
       [ 4,  4,  3,  6,  5,  7, 10,  9,  4, 11],
       [ 5, 10,  7, 11,  7,  6,  8,  7, 10,  4],
       [ 2,  9,  8, 11,  6,  8,  2,  4,  8, 11],
       [ 5,  2, 10,  9,  7,  4,  8,  8,  8,  5],
       [ 2,  7,  7, 10,  4,  4,  9,  7,  8,  3]])

# 二维与一维拼接

In [89]:
ar123=np.random.randint(10,20,(8,5))
ar_1dim=np.random.randint(30,40,8)
ar123,ar_1dim

(array([[19, 14, 11, 14, 13],
        [18, 13, 16, 11, 12],
        [18, 16, 17, 10, 15],
        [16, 15, 17, 18, 14],
        [11, 15, 18, 11, 19],
        [12, 11, 13, 17, 18],
        [19, 10, 15, 19, 13],
        [11, 16, 11, 11, 16]]),
 array([36, 30, 32, 37, 36, 33, 35, 39]))

In [93]:
np.hstack([ar123,ar_1dim.reshape(8,1)])

array([[19, 14, 11, 14, 13, 36],
       [18, 13, 16, 11, 12, 30],
       [18, 16, 17, 10, 15, 32],
       [16, 15, 17, 18, 14, 37],
       [11, 15, 18, 11, 19, 36],
       [12, 11, 13, 17, 18, 33],
       [19, 10, 15, 19, 13, 35],
       [11, 16, 11, 11, 16, 39]])

In [94]:
np.column_stack([ar123,ar_1dim])

array([[19, 14, 11, 14, 13, 36],
       [18, 13, 16, 11, 12, 30],
       [18, 16, 17, 10, 15, 32],
       [16, 15, 17, 18, 14, 37],
       [11, 15, 18, 11, 19, 36],
       [12, 11, 13, 17, 18, 33],
       [19, 10, 15, 19, 13, 35],
       [11, 16, 11, 11, 16, 39]])

# 数据分割

## hsplit和vsplit

In [95]:
ar30=np.random.randint(20,31,(6,8))
ar30

array([[20, 30, 23, 24, 27, 21, 28, 24],
       [21, 23, 21, 24, 23, 30, 25, 29],
       [26, 22, 24, 22, 28, 30, 23, 30],
       [27, 26, 29, 24, 30, 24, 25, 20],
       [26, 23, 22, 22, 24, 25, 23, 22],
       [27, 20, 20, 24, 25, 24, 26, 30]])

In [97]:
np.hsplit(ar30,2)

[array([[20, 30, 23, 24],
        [21, 23, 21, 24],
        [26, 22, 24, 22],
        [27, 26, 29, 24],
        [26, 23, 22, 22],
        [27, 20, 20, 24]]),
 array([[27, 21, 28, 24],
        [23, 30, 25, 29],
        [28, 30, 23, 30],
        [30, 24, 25, 20],
        [24, 25, 23, 22],
        [25, 24, 26, 30]])]

In [98]:
np.vsplit(ar30,2)

[array([[20, 30, 23, 24, 27, 21, 28, 24],
        [21, 23, 21, 24, 23, 30, 25, 29],
        [26, 22, 24, 22, 28, 30, 23, 30]]),
 array([[27, 26, 29, 24, 30, 24, 25, 20],
        [26, 23, 22, 22, 24, 25, 23, 22],
        [27, 20, 20, 24, 25, 24, 26, 30]])]

In [100]:
np.split(ar30,2,axis=0)

[array([[20, 30, 23, 24, 27, 21, 28, 24],
        [21, 23, 21, 24, 23, 30, 25, 29],
        [26, 22, 24, 22, 28, 30, 23, 30]]),
 array([[27, 26, 29, 24, 30, 24, 25, 20],
        [26, 23, 22, 22, 24, 25, 23, 22],
        [27, 20, 20, 24, 25, 24, 26, 30]])]

In [101]:
np.split(ar30,2,axis=1)

[array([[20, 30, 23, 24],
        [21, 23, 21, 24],
        [26, 22, 24, 22],
        [27, 26, 29, 24],
        [26, 23, 22, 22],
        [27, 20, 20, 24]]),
 array([[27, 21, 28, 24],
        [23, 30, 25, 29],
        [28, 30, 23, 30],
        [30, 24, 25, 20],
        [24, 25, 23, 22],
        [25, 24, 26, 30]])]